### ISSUE TITLE
Unable to load WatchUI with RIDE

### ISSUE THREAD

**Issue by a9038889** [Tesena-smart-testing/WatchUI#103]
**Describe the bug**
Unable to load WatchUI with RIDE

**To Reproduce**
1. pip install WatchUI 
2. Open RIDE
3. Click Library
4. Importing test library "WatchUI" failed

RIDE Log
20220521 09:17:46.470 [WARN]: Importing test library "WatchUI" failed

Traceback (most recent call last):
list index out of range
  File "C:\Users\Andy Su\AppData\Local\Programs\Python\Python37\lib\site-packages\robotide\spec\librarymanager.py", line 87, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Users\Andy Su\AppData\Local\Programs\Python\Python37\lib\site-packages\robotide\spec\libraryfetcher.py", line 32, in get_import_result
    ) for kw in lib.handlers]
  File "C:\Users\Andy Su\AppData\Local\Programs\Python\Python37\lib\site-packages\robotide\spec\libraryfetcher.py", line 32, in <listcomp>
    ) for kw in lib.handlers]
  File "C:\Users\Andy Su\AppData\Local\Programs\Python\Python37\lib\site-packages\robotide\spec\libraryfetcher.py", line 43, in _parse_args
    parsed[index] = parsed[index] + '=' + unicode(value)

**Expected behavior**
Successfully loaded WatchUI

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 
 - Started RIDE 1.7.4.2 using python version 3.7.4 with wx version 4.0.6 in win32.
 - WatchUI 1.0.12

**Comment by radekBednarik** [comment]
Hi, I see that you are using Python 3.7.
We are supporting Python 3.9. Please try that version, if you can.
Also, we currently do not test against compatibility with RIDE.
