### ISSUE TITLE
 ImportError: libcrypt.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SerjPrecog** [Tesena-smart-testing/WatchUI#122]
**Describe the bug**
watchui couldn't be imported after 23/08/2023. Looks like it takes more recent version of PyMuPDF=1.23.0. And this library uses libcrypt.so.2 which as far as I understood is not supported by Ubuntu 20/22 and isn't official version of openssl (1.1 or 3 are used). freeze with version in requirements.txt PyMuPDF==1.22.5 helped to fix this error

**To Reproduce**
pip install watchui
run test with Compare Images

**Expected behavior**
successful run

**Logs**
[ ERROR ] Error in file '/home/user/Projects/automated-tests/suites/browser/application/components/power_user/components/data_viewer/data_viewer.robot' on line 7: Importing library 'WatchUI' failed: ImportError: libcrypt.so.2: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/user/Projects/automated-tests/venv/lib/python3.9/site-packages/WatchUI/__init__.py", line 1, in <module>
    from WatchUI.WatchUI import WatchUI
  File "/home/user/Projects/automated-tests/venv/lib/python3.9/site-packages/WatchUI/WatchUI.py", line 6, in <module>
    from .keywords import Image, Pdf, Tesseract
  File "/home/user/Projects/automated-tests/venv/lib/python3.9/site-packages/WatchUI/keywords/__init__.py", line 5, in <module>
    from .PDF import Pdf
  File "/home/user/Projects/automated-tests/venv/lib/python3.9/site-packages/WatchUI/keywords/PDF.py", line 6, in <module>
    import fitz
  File "/home/user/Projects/automated-tests/venv/lib/python3.9/site-packages/fitz/__init__.py", line 22, in <module>
    from fitz.fitz import *
  File "/home/user/Projects/automated-tests/venv/lib/python3.9/site-packages/fitz/fitz.py", line 14, in <module>
    from . import _fitz

**Desktop (please complete the following information):**
#85~20.04.1-Ubuntu SMP Mon Jul 17 09:42:39 UTC 2023
Browser Chrome 115.0.5790.110

**Additional context**

**Comment by procesor2017** [comment]
Hey. Hey,
unfortunately this is a dependency error that we can't control, the only thing that can be done is to set the same solution as you did.

**Comment by SerjPrecog** [comment]
Hi! You could fixate dependencies in your project for tested ones to prevent new issues on dependencies update, like we have here.
